project:
  type: book
  output-dir: docs
book:
  title: "Prevents enkät för organisatorisk och social arbetsmiljö"
  subtitle: "Psykometrisk analys & datavisualisering"
  repo-url: "https://github.com/pgmj/PreventOSA"
  sidebar:
    style: floating
    search: true
  author:
    - name: 'Magnus Johansson'
      affiliation: 'RISE Research Institutes of Sweden'
      affiliation-url: 'https://ri.se/shic'
      orcid: '0000-0003-1669-592X'
    - name: 'Simon Karlsson'
      orcid: '0000-0002-3817-380X'
      affiliation: 'RISE Research Institutes of Sweden'
      affiliation-url: 'https://www.ri.se/kbm'
  date: 2023-06-05
  date-format: iso
  doi: '10.5281/zenodo.8220620'

  chapters:
  - index.qmd
  - sammanfattning.qmd
  - 01_arborg/01_arborg.qmd
  - 02_arbkrv/02_arbkrv.qmd
  - 03_mpvrk/03_mpvrk.qmd
  - 04_std/04_std.qmd
  - 05_rec/05_rec.qmd
  - 06_ldrskp/06_ldrskp.qmd
  - 07_knskputv/07_knskputv.qmd
  - 08_krbet/08_krbet.qmd
  - 09_psyktry/09_psyktry.qmd
  - cfa/osaCFA.qmd
  - 10_arbkrv_rec/10_arbkrv_rec.qmd
  - 11_psyktry_std_mp/11_psyktry_std_mp.qmd
  - visualisering/osaviz.qmd
  - osaVizFinal.qmd
  - software.qmd

format:
  html:
    toc: true
    toc-depth: 3
    code-tools: false
    code-fold: true
    number-sections: true
    layout-align: left
    page-layout: full
    logo: rise_logo_quarto.png
    mainfont: 'Lato'
    monofont: 'Roboto Mono'
    linestretch: 1.6
    theme:
      - materia
      - custom.scss
    css: styles.css
    link-external-newwindow: true
    fig-dpi: 96
    crossref-sec-prefix: "Sektion"
    toc-title: "Innehållsförteckning"
    crossref-fig-title: "Figur"
    crossref-tbl-title: "Tabell"
    callout-note-title: "Beskrivning"
